version: '2'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - dexshare

  app:
    image: dexshare:latest
    build: .
    environment:
      - MONGODB_HOST=mongodb
    ports:
      - "8080:8080"
    networks:
      - dexshare
    depends_on:
      - mongodb

networks:
  dexshare:
